// src/samples/angular/movies.js
import { Component, Input } from '@angular/core'

@Component({
  selector: 'app-movies',
  template: `
    <div class="divide-y divide-gray-100">
      <app-nav>
        <app-nav-item routerLink="/new" [isActive]="true">New Releases</app-nav-item>
        <app-nav-item routerLink="/top">Top Rated</app-nav-item>
        <app-nav-item routerLink="/picks">Vincent’s Picks</app-nav-item>
      </app-nav>
      <app-list>
        <app-list-item *ngFor="let movie of movies" [movie]="movie"></app-list-item>
      </app-list>
    </div>
  `,
})

export class MoviesComponent {
  @Input() movies!: {
    image: string
    title: string
    starRating: string
    rating: string
    year: string
    genre: string
    runtime: string
    cast: string
  }[]
}

// src/samples/react/movies.jsx
import Nav from './Nav.js'
import NavItem from './NavItem.js'
import List from './List.js'
import ListItem from './ListItem.js'

export default function Movies({ movies }) {
  return (
    <div className="divide-y divide-gray-100">
      <Nav>
        <NavItem href="/new" isActive>New Releases</NavItem>
        <NavItem href="/top">Top Rated</NavItem>
        <NavItem href="/picks">Vincent’s Picks</NavItem>
      </Nav>
      <List>
        {movies.map((movie) => (
          <ListItem key={movie.id} movie={movie} />
        ))}
      </List>
    </div>
  )
}
